@startuml ER Diagram

entity users {
	* * id uuid [pk]
  	* username varchar
  	* password_hash varchar
  	* nickname varchar
  	* email varchar
  	phone_number varchar
  	profile_picture varchar
}

entity stations {
	* * id uuid [pk]
  	* username varchar
  	* password_hash varchar
  	* nickname varchar
  	* email varchar
  	phone_number varchar
  	profile_picture varchar
}

entity users_stations {
  user_id uuid
  station_id uuid
  role_id uuid
}

entity fuel_types {
  * id uuid [pk]
  description varchar
}

entity fuel_prices {
  * id uuid [pk]
  fuel_type_id varchar
  station_id varchar
  price decimal
  creation_user_id varchar
  creation_date datetime
}

entity addresses {
  * id uuid [pk]
  street_name varchar
  street_number varchar
  zip_code varchar
  district varchar
  city_id varchar
  latitude float
  longitude float
}

entity cities {
  * id uuid [pk]
  name varchar
  state_id varchar
}

entity states {
  * id uuid [pk]
  name varchar
  country_id varchar
}

entity countries {
  * id uuid [pk]
  name varchar
}

@enduml